# deveops - pipeline

name: $(date:yyyyMMdd)$(rev:rr) #201907.00

stages:
  - stage: 'build'
    displayName: 'built-mvc'
    condition: succeeded()
    jobs:
      - job:
        condition: succeeded()
        displayName: 'build-job'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              dotnet build 

  - stage: 'test'
    displayName: 'test-mvc'
    condition: succeeded()
    jobs:
      - job:
        condition: succeeded()
        displayName: 'test-job'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              dotnet test /p:CollectCoverage=true
  - stage: 'pack'
    displayName: 'pack-mvc'
    condition: succeeded()
    jobs:
      - job:
        condition: succeeded()
        displayName: 'pack-job'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              echo 'pack passed' 

  - stage: 'deploy'
    displayName: 'deploy-mvc'
    condition: succeeded()
    jobs:
      - job:
        condition: succeeded()
        displayName: 'deploy-job'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              echo 'deploy passed' 
trigger:
- master
