# deveops - pipeline

name: $(date:yyyyMMdd)$(rev:rr) #201907.00

stages:
  - stage: 'build'
    displayName: 'built-mvc'
    condition: succeded()
    jobs:
      - job:
        condition: succeded()
        displayName: 'build-job'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              echo 'build passed' 

  - stage: 'test'
    displayName: 'test-mvc'
    condition: succeded()
    jobs:
      - job:
        condition: succeded()
        displayName: 'test-job'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              echo 'test passed' 
  - stage: 'pack'
    displayName: 'pack-mvc'
    condition: succeded()
    jobs:
      - job:
        condition: succeded()
        displayName: 'pack-job'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              echo 'pack passed' 

  - stage: 'deploy'
    displayName: 'deploy-mvc'
    condition: succeded()
    jobs:
      - job:
        condition: succeded()
        displayName: 'deploy-job'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              echo 'deploy passed' 
trigger:
- master
